name: All CI Jobs
agent:
  type: Unity::VM
  image: cds-ops/ubuntu-18.04-agent:latest
  flavor: m1.large
commands:
- echo hello
triggers:
  branches:
    only:
    - /.*/
    except: []
artifacts: {}
variables: {}
parameters: {}
dependencies:
- .yamato/Tests_Linux_TestVSCodePackage_scripting_new-codeeditor-api_ci.yml
