name: All CI Jobs
agent:
  type: Unity::VM
  image: cds-ops/ubuntu-18.04-agent:stable
  flavor: m1.large
commands:
- echo hello
triggers:
  branches:
    only:
    - /.*/
    except: []
artifacts: {}
variables: {}
parameters: {}
dependencies:
- .yamato/Tests_Windows_TestVSCodePackage_scripting_external-script-editor-api_ci.yml
