name: All CI Jobs
agent:
  type: Unity::VM
  image: sdet/gamecode_win10:v0.2.1-91595
  flavor: m1.xlarge
commands:
- echo hello
triggers:
  branches:
    only:
    - /.*/
    except: []
artifacts: {}
variables: {}
parameters: {}
dependencies:
- .yamato/Tests_Windows_TestVSCodePackage_scripting_external-script-editor-api_ci.yml
